### ISSUE TITLE
misleading example to start a race

### ISSUE THREAD

**Issue by alexandramartinez** [rhoegg/anypoint-race-api#10]
the example says
```
{
  "racerUrl": "https://racer-sylvester-api-yx2y1s.5sc6y9-1.usa-e2.cloudhub.io/api/"
}
```
but i had to send
```
{
  "racerUrl": "http://anypoint-racer-app.us-e2.cloudhub.io/api"
}
```

![image](https://github.com/rhoegg/anypoint-race-api/assets/3922764/5ce6b39b-c126-42b5-b880-4c676aa7c29a)

**Comment by rhoegg** [comment]
Fixed the example URL, thanks for reporting!
