### ISSUE TITLE
Start a new race.

### ISSUE THREAD

**Issue by GeorgeJeffcock** [rhoegg/anypoint-race-api#9]
Season 2

Start a new race. for example post to https://api-race-yxwy1s.5sc6y6-4.usa-e2.cloudhub.io/api/racers/9cbaca0a-0c4e-405a-8017-fcbe40386e3f/start

with body set to application/json

{
    "racerUrl": "https://enceakcvz61fk.x.pipedream.net"
}

always returns OK - and httpstatus 500

Passed security and correctly get 429 if request to frequently which means we are getting passed the mule gateway but am getting problems in the implementation

the supplied webhook (requestbin) is never hit

**Comment by GeorgeJeffcock** [comment]
if I send the request to a requestbin it looks like the following:

POST
/racers/9cbaca0a-0c4e-405a-8017-fcbe40386e3f/start

Headers
Host: enceakcvz61fk.x.pipedream.net
X-Amzn-Trace-Id: Root=1-650cad8c-3548ccdb208e4c9e4974c8ee
Content-Length: 59
client_id: acb2b230e6e546118cf7b157a2313ca0
client_secret: 6d0a69fa537749939XXXXXX02211cA7
Content-Type: application/json
Postman-Token: 05b23605-1423-4536-b798-cef3390c5788

Body
{
    "racerUrl": "https://enceakcvz61fk.x.pipedream.net"
}

**Comment by GeorgeJeffcock** [comment]
check logs for x-correlation-id  b9d44065-b6d6-440b-b2ad-e4515eab513b

**Comment by ryandcarter** [comment]
+1

**Comment by pranav-davar** [comment]
+1

**Comment by alexandramartinez** [comment]
@rhoegg ?

**Comment by rhoegg** [comment]
Thanks for submitting the issue! Working on it now

**Comment by rhoegg** [comment]
Aha, this looks like a bad error message when your Racer API does not return a good racerId in the response.  I think the error message is much improved in #8 (thanks @rrerusu!)

I'll merge it and deploy

**Comment by rhoegg** [comment]
It was a bug with the redis persistence! Now season 2 can begin, it's fixed!
